# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45169552e19f8584af4c1dc717fbb73dd64053976036f964e9e361f48fab764eef8562afa8b0912e4861c95cd18ce0195b8a957734f1f536b5d0f8c1c73b9768

test:
  secret_key_base: fb9238ae23a42ffbb0bb9d6ed570d03cba103af9594dbc56ae43d8d4ef52eefa329f8503aaf5195dc91f0af01cc66ebfc7aef3b6cc38e1cba866c6ff3014cfc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
